### ISSUE TITLE
Implement rand::Rand

### ISSUE THREAD

**Issue by termoshtt** [rust-num/num-complex#12]
`num-complex::Complex<T>` should implement `rand::Rand` if `T: Rand` is assured.

**Comment by cuviper** [comment]
As an optional feature, sure!

**Comment by vks** [comment]
`Rand` is likely to get deprecated.

**Comment by cuviper** [comment]
@vks Do you have more information about that?  What's the replacement?

**Comment by vks** [comment]
@cuviper It will be replaced with something similar, see https://github.com/dhardy/rand/issues/83.

**Comment by cuviper** [comment]
Hmm.  It seems fine to go ahead and support `rand` as it exists _today_, and we can migrate to the new thing later along with everyone else.  With a shim crate it's even possible to support both.

**Comment by shingtaklam1324** [comment]
@vks If we decide to stick to supporting Rust 1.8 for num-complex, that won't be an issue as rand v0.4+ won't even compile on rustc 1.8.0
