### ISSUE TITLE
Undue overflow or underflow on complex division

### ISSUE THREAD

**Issue by hydeik** [rust-num/num-complex#23]
Complex division `c1 / c2` might return an incorrect value when `c2.norm_sqr()` overflows or underflows.
For instance,

``` rust
  extern crate num;
  use num::Complex;

  fn main() {
      let z1 = 1_f64 / Complex::new(1e300_f64, 1e300_f64);
      println!("z1 = {:e}", z1);
      // (expected output) z1 = 5e-301+5e-301i
      // (actual output)   z1 = 0e0+0e0i

      let z2 = 1_f64 / Complex::new(1e-301_f64, 1e-301_f64);
      println!("z2 = {:e}", z2);
      // (expected output) z2 = 5e300+5e300i
      // (actual output)   z2 = inf-infi
  }
```

**Comment by cuviper** [comment]
I know there are more sophisticated algorithms out there, but this is pretty accurate for your examples:

```rust
fn finv<T: Float>(c: Complex<T>) -> Complex<T> {
    let norm = c.norm();
    c.conj() / norm / norm
}

fn fdiv<T: Float>(a: Complex<T>, b: Complex<T>) -> Complex<T> {
    a * finv(b)
}
```

**Comment by hydeik** [comment]
Thank you for detailed explanation.

I understand the reason why the current implementation uses the naive algebraic formula.
It would be nice if alternative method for `T: Float` is provided immediately in the library so that we could avoid this problem. 
(`fdiv` seems to be good for method name.)

Of course, implementing specialized `Div` for `T: Float` would be more elegant solution after Rust stabilized specialization.

**Comment by cuviper** [comment]
@benruijl -- Have you tested whether the `fdiv` I gave above does work better for you?  I can add them as methods, but they should work fine as the standalone functions given.

**Comment by benruijl** [comment]
@cupiver, I did. Your snippet works for me and I would like to see it included in the library.
