### ISSUE TITLE
Release num-complex 0.2 to crates.io.

### ISSUE THREAD

**Issue by sebcrozet** [rust-num/num-complex#24]
I was wondering what development is still necessary on num-complex before a release to `crates.io` can happen? I'd love to see the recent changes released as this would allow me to make `nalgebra` support `#![no_std]` as well!

**Comment by cuviper** [comment]
Mostly, I'm just hesitant to call it ready. 😅 But if it's working for `nalgebra`, that's a pretty good vote of confidence.  I'll go over it again today and see if there's anything else I think needs a breaking change.

**Comment by cuviper** [comment]
Published!

**Comment by sebcrozet** [comment]
Great, thanks !
