### ISSUE TITLE
On the validity of the Complex modulus as implemented

### ISSUE THREAD

**Issue by ChristopherRabotin** [rust-num/num-complex#31]
First of all, please excuse any possible mathematical misunderstanding here as the details of complex numbers is not my specialty.

While working on an implementation of the [remainder operation](https://github.com/novacrazy/dual_num/issues/3) for another _type_ ([Rooney 1978](http://journals.sagepub.com/doi/10.1068/b050089) and [Fike et al. 2011](http://adl.stanford.edu/hyperdual/Fike_AIAA-2011-3807.pdf)) of complex numbers called [dual numbers](https://en.wikipedia.org/wiki/Dual_number), I decided to check the implementation of the remainder operations in `num-complex`. From my reading of the [relevant code](https://github.com/rust-num/num-complex/blob/master/src/lib.rs#L544), an attempt is made to find the closest [Gaussian integers](https://en.wikipedia.org/wiki/Gaussian_integer). However, from my limited understanding, Gaussian integers are only valid if both parts of the complex number are integers (in Z), but `num-complex` seems to allow the remainder operation for any complex number regardless of whether or not both the real and imaginary part is an integer. Although there is an "extension" of Gaussian integers to [Gaussian rationals](https://en.wikipedia.org/wiki/Gaussian_integer#Gaussian_rationals), my (limited) understanding is that any Gaussian rational must be in fact a Gaussian integers where both parts of the complex number must be integers and not any kind of rational.

**Question:** Am I misunderstanding Gaussian rationals? (Probably.) And if not, then shouldn't the `rem` implementation be limited to types `T` where T is an integer?

Thanks.

**Comment by cuviper** [comment]
The choice we made for `Rem` here is probably not as mathematically rigorous as you seem to assume.  It was more of a pragmatic decision to do something that seemed reasonable, in large part just to enable the `Num` trait which requires `Rem`.  I think what we have is a useful definition, but I would not make very strong mathematical claims about it.

You can see some of the discussion in rust-num/num#327 -- don't forget to "show outdated" comments.  One thing I pushed for was the `Rem` with a purely real `Complex<T>` should have the same result as `Rem` of direct `T` values.

You're right that Gaussian integers have both real and imaginary parts as integers.  The point of this implementation of `Rem` was not to act as if the whole operation was on integers; just to find the result of division as a Gaussian and compute a remainder from that.  Maybe it's misleading to mention Gaussian here at all, where really we're just truncating the division.

The idea is similar to how `Rem` works with floating point numbers.  For example, try 3.55 % 1.1 -- the truncated division 3.55/1.1 is 3, so 3.55 % 1.1 = 3.55 - 1.1*3 = 0.25.
