### ISSUE TITLE
Add MulAdd

### ISSUE THREAD

**Issue by benruijl** [rust-num/num-complex#37]
[MulAdd ](https://doc.rust-lang.org/std/primitive.f64.html#method.mul_add)provides a way to reduce rounding errors when adding and multiplying.

Here is the related Julia code:
```
muladd(z::Complex, w::Complex, x::Complex) =
    Complex(muladd(real(z), real(w), real(x)) - imag(z)*imag(w), # TODO: use mulsub given #15985
            muladd(real(z), imag(w), muladd(imag(z), real(w), imag(x))))
```

**Comment by Schultzer** [comment]
@cuviper I would like to impl this but I think we should make the trait work on no_std first [#102](https://github.com/rust-num/num-traits/issues/102)

**Comment by cuviper** [comment]
These are independent concerns. The traits do exist in `no_std`, so you can write a generic implementation here regardless of the specific underlying types.

**Comment by Schultzer** [comment]
I'm kinda stuck on the impl

I get this error 

I'm not really sure what I'm doing wrong because I expect that MulAdd will return `T` but it returns `<T as traits::MulAdd>::Output`.
```
error[E0369]: binary operation `-` cannot be applied to type `<T as traits::MulAdd>::Output`
```

```
impl<T: Clone + Num + MulAdd> MulAdd<Complex<T>> for Complex<T> {
    type Output = Complex<T>;

    #[inline]
    fn mul_add(self, other: Complex<T>, x: Complex<T>) -> Complex<T> {
        let re = self.re.clone().mul_add(other.re.clone(), x.re.clone()) - self.im.clone() * other.im.clone(); // FIXME: use mulsub when available in rust
        let im = self.re.mul_add(other.im, self.im.mul_add(other.re, x.im));
        Complex::new(re, im)
    }
}
```

**Comment by cuviper** [comment]
Use `T: MulAdd<Output = T>`, otherwise the output is unconstrained.

**Comment by redweasel** [comment]
Note to future readers: Reduced rounding errors have been mentioned, but in the closing commit, the tests test against the same badly rounded operation with the same level of precision. This function has not reduced rounding error (at least not in any tested case). It may just be a performance boost on some (most) machines.
