### ISSUE TITLE
sqrt() approximation

### ISSUE THREAD

**Issue by nackstein** [rust-num/num-complex#59]
Hello,
I'm not sure if it's a bug or a known rounding behavior.
If I compute the sqrt() of a complex number -9+0i the correct solution should be 0+3i
but with this module (I used num crate) I got:
0.00000000000000018369701987210297+3i

As far as I know some math lib implement hard-coded case for some exact value.
Did you considered doing the same?

Luigi

**Comment by cuviper** [comment]
That's rounding error -- we convert to polar to perform the operation and then convert back. So -9+0i = 9e<sup>iπ</sup>, then the square root is 3e<sup>iπ/2</sup> = 0+3i. However, those irrational angles can't be precisely represented, so the conversions are slightly inaccurate.

But yes, I think we could add a special case when the input has zero imaginary value. The principal square root of a positive real is a positive real, and for a negative real it is a positive imaginary. Then we wouldn't have any loss beyond the scalar `Float::sqrt` itself.
