### ISSUE TITLE
README suggests version 0.3, but crates.io still lists 0.2.4

### ISSUE THREAD

**Issue by evertrol** [rust-num/num-complex#76]
Using version 0.3 as suggested in the README will result in a failed build.
I guess the README is a bit ahead of itself (and its repository).

**Comment by cuviper** [comment]
The repository is on `0.3.0-pre` for #70. It's a little unfortunate that this is ahead of the published crate, but at least the [README shown on crates.io](https://crates.io/crates/num-complex) is self-consistent.

**Comment by evertrol** [comment]
Ah, yes, apologies: I have a tendency of immediately going to the homepage or documentation page from the list of packages overview page, instead of visiting the individual package page on crates.io.

**Comment by cuviper** [comment]
Released!
