### ISSUE TITLE
Update to Serde 1.0

### ISSUE THREAD

**Issue by cuviper** [rust-num/num-complex#8]
See rust-num/num#281, and this was previously in the `next` branch after rust-num/num#305.

**Comment by cuviper** [comment]
And this has been re-started in #7.

**Comment by shingtaklam1324** [comment]
A quick check through changing the deps for serde to `1.0.0` shows the following errors:

- [ ] It breaks for `rustc 1.8.0`, I dont' think this is priority anymore but it may still be an issue
- [ ] The signature for serialize has been changed from `fn(&mut S)` to `fn(S)`
- [ ] The signature for deserialize has been chnaged from `fn(&mut D)` to `fn(D)`
- [ ] Lifetime specifiers are needed for `serde::Serialize`
- [ ] Lifetime specifiers are needed for `serde::Deserialize`

These are the errors that the compiler throws, but I haven't checked for any functional differences yet.

**Comment by cuviper** [comment]
Oh sorry, this was already done in #7.  Are you not seeing this on the master branch?

**Comment by shingtaklam1324** [comment]
Oh... My fork was quite a bit behind... 
The issue being open may have confused others as well.
