### ISSUE TITLE
Proposal: bytemuck support

### ISSUE THREAD

**Issue by ajtribick** [rust-num/num-complex#86]
It would be useful to have optional support for the `Pod` trait from the [bytemuck](https://github.com/Lokathor/bytemuck) crate, at least for `Complex32` and `Complex64` (I'd guess that bytemuck's requirements around padding might make generic support trickier).

My use case here is reading/writing buffers with `Complex32` values to send to the GPU for processing with compute shaders. It's relatively easy to work around this, but it would be a nice-to-have.

**Comment by cuviper** [comment]
Sounds good, and I think even generic support will be fine -- it's `#[repr(C)]` with two identical fields, so there's never any padding.

**Comment by cuviper** [comment]
This was added in #100 and published in 0.4.1.
