### ISSUE TITLE
Implement From<U> for Complex<T>

### ISSUE THREAD

**Issue by fasiha** [rust-num/num-complex#9]
Right now, this crate lets us convert real types like `i32` to `Complex<i32>` by implementing `From<T> for Complex<T>` ([source](https://docs.rs/num-complex/0.1.41/src/num_complex/lib.rs.html#407-409)). Awesome!

Would you consider adding mixed-type conversions, i.e., implement `From<U> for Complex<T>`? Ideally all the implementors from [std::convert::From](https://doc.rust-lang.org/std/convert/trait.From.html#implementors) would be available so one could convert, e.g., `3i16` to `Complex64`, etc.

I think this could be relevant to #4 but also help more issues in that vein. (I ran into it when attempting to create mixed-domain/mixed-precision vector-addition, and couldn't implement this in my own library because of the orphan rule.)

I can take a shot at a pull request, if you think this is worthwhile and has some possibility of being done correctly by a Rust noob?

**Comment by cuviper** [comment]
I don't think it's possible, because of the core `impl From<T> for T`.  At least, when I try to replace the current implementations of `From` with:

```rust
impl<T: Clone + Num + From<U>, U> From<U> for Complex<T> {
    #[inline]
    fn from(re: U) -> Complex<T> {
        Complex { re: T::from(re), im: T::zero() }
    }
}
```

I get:

```text
error[E0119]: conflicting implementations of trait `std::convert::From<Complex<_>>` for type `Complex<_>`:
   --> src/lib.rs:403:1
    |
403 | / impl<T: Clone + Num + From<U>, U> From<U> for Complex<T> {
404 | |     #[inline]
405 | |     fn from(re: U) -> Complex<T> {
406 | |         Complex { re: T::from(re), im: T::zero() }
407 | |     }
408 | | }
    | |_^
    |
    = note: conflicting implementation in crate `core`
```

But if you can figure out how to make that work, I'll consider it!

**Comment by fasiha** [comment]
Ah, I see, very interesting! I found a reasonably lucid explanation of the problem in [this blog post](https://ferrisellis.com/posts/rust-implementing-units-for-types/) (search for 'conflicting implementations of trait', and the links therein), though in a slightly different context.

If I understand, Rust has to allow for the possibility that, when we say `impl<T, U> From<U> for Complex<T>`, hypothetically `U == Complex<T>`, in which case the new implementation is a redefinition of `impl<T> From<T> for T` from core.

How frustrating!

The solution in that blog post, however, is to implement *not* `From<U>` but `From<&U>`, a reference to the "smaller" type. You already have `impl<'a, T: Clone + Num> From<&'a T> for Complex<T>` ([source](https://docs.rs/num-complex/0.1.41/src/num_complex/lib.rs.html#412-417)), which you could replace with a `impl<'a, U, T>` version, without any loss of generality (I think):
```rust
impl<'a, U, T> From<&'a U> for Complex<T>
where
    U: Clone + Num,
    T: Num + From<U>,
{
    #[inline]
    fn from(re: &'a U) -> Complex<T> {
        Complex {
            re: T::from(re.clone()),
            im: T::zero(),
        }
    }
}
```
Then, the following test passes:
```rust
    #[test]
    fn test_from() {
        let n = 3i16;
        let c: Complex64 = Complex::from(&n);
        let d = Complex { re: 3., im: 0. };
        assert_eq!(c.re, d.re);
        assert_eq!(c.im, d.im);

        let e = Complex64::from(&2.2f64);
        assert_eq!(e.re, 2.2f64);
        assert_eq!(e.im, 0.0);
    }
```

The downside is that you'd have to remove *both* `From for Complex` implementations that you have currently, including the `impl<T: Clone + Num> From<T> for Complex<T>`, because this latter conflicts with the one above. That is, you wouldn't be able to call `Complex::from` on values, only references.

Do you think this is too high a price to pay? The reward would be mixed-precision/mixed-domain capability, so you can add `Complex64` to `i16`, etc.

**Comment by cuviper** [comment]
Note that scheme hurts type inference, as you had to force it to `Complex64` in both of your examples.

>     let c: Complex64 = Complex::from(&n);
>     let e = Complex64::from(&2.2f64);

The partner trait `Into` is also less ergonomic when you add the `&` indirection.  Imagine you had a `trait Foo: Into<Complex64>`.  Now you'd have to write `trait Foo where for<'a> &'a Self: Into<Complex64>`.  Per rust-lang/rust#20671, that `where` clause also can't be implied by `Foo`, but has to be repeated everywhere `Foo` is used.

Do you *need* this to use a direct `From`?  You should already be able to do the two-layer conversion yourself, `Complex::from(f64::from(n))`.  It would also be easy to add a plain method along these lines, avoiding a breaking change to `From` altogether, something like:

```rust
impl<T: Clone + Num> Complex<T> {
   pub fn from_real<R: Into<T>>(re: R) -> Self {
      Complex::from(re.into())
   }
}
```

**Comment by fasiha** [comment]
Ahh, you are absolutely right—and there we see the difference between the noob and the guru 😅!

Let me press on with implementing more of my library (a BLIS port to Rust) with your crate as it is now, and think a bit harder about how to do mixed-precision and mixed-mode. I *think* that the right place to tweak num-complex would be in the implementations of `Add`, `Sub`, etc., so that we could add real+complex, complex+real, and complex+complex with different types, as long as `From` is available between the underlying real types—but let me think about it a bit more to see if I'm right. Thanks for your thoughtfulness and advice!

**Comment by cuviper** [comment]
No need to worry about noobs and gurus -- we'll come to agreement either way. :smile:

> I think that the right place to tweak num-complex would be in the implementations of Add, Sub, etc., so that we could add real+complex, complex+real, and complex+complex with different types, as long as From is available between the underlying real types

That would be atypical for Rust -- note that the operators for primitive integers and floats don't do `From` conversions either.  Idiomatic Rust generally prefers explicit numeric conversions.

You might then ask why we should bother with `real OP complex` and `complex OP real` at all, but there's at least some argument that the operation can be implemented more simply or more accurately than `complex OP complex`.  (Even if we don't do that yet, as noted in #4.)

**Comment by fasiha** [comment]
I understand better now how Rust asking you to do explicit conversion is an important precedent. My concern would be in dealing with vectors (or matrixes or tensors) where speed is paramount, e.g., when I have a billion `Complex<f32>` and a billion `i16`s and want to add the latter into the former quickly, I don't want to convert before handing them off to my linear algebra `addv` routine. Also, I'd love it if that `addv` function not need to know about the types of its two inputs, just that lower-level they can be `From`ed/`Into`d.

(Perhaps some useless background—right now, BLIS is a C99 library and does not yet do mixed-mode/mixed-precision arithmetic. Its `addv` can only add the exact same types. With Rust and your crate, my `addv` can at least do mixed-mode! That is, I can add `Complex<f64>` and `f64` vectors, with my noob-level skill with generics/traits. Mixed-precision would be the next desideratum.)

Again, many thanks for being so generous with your time!
