### ISSUE TITLE
Release a 1.0 version

### ISSUE THREAD

**Issue by obsgolem** [rust-num/num-complex#94]
This library appears to be the de-facto standard for complex numbers. Downstreams include ndarray and nalgebra. I just ran into an issue where ndarray is using an older version of approx, where if you turned on its num-complex feature it tried to use an older version of num-complex. If you aren't planning on making breaking changes then it would be nice if you could bump to a 1.0 version so that feature additions don't require upstreams to bump their versions. See also https://github.com/brendanzab/approx/issues/70.

**Comment by cuviper** [comment]
Just as `approx` cited `num-complex`, I must cite our public dependencies as well. It's uncertain about `num-traits` (which I also control), but `rand` does seem like it will eventually want to update to 0.9 and later.
