### ISSUE TITLE
Changing display format to a more compact form.

### ISSUE THREAD

**Issue by ErikBuer** [rust-num/num-complex#96]
Hi,
I am new to Rust, and open source contribution, so please bear with me..

When debugging arrays of complex numbers i find the formatting to be unnecessarily long, making it hard to see what is going on in the data. See the example below.

I therefore propose to change the debug and display formatting to `a+bi`, e.g. `1+2i`.

Note that in the example below, Github doesn't wrap the line.
```
stderr:
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `[Complex { re: 1, im: 0 }, Complex { re: 1, im: 0 }, Complex { re: 1, im: 0 }, Complex { re: 1, im: 0 }, Complex { re: 1, im: 0 }, Complex { re: 1, im: 0 }, Complex { re: 1, im: 0 }, Complex { re: 1, im: 0 }, Complex { re: 1, im: 0 }, Complex { re: 1, im: 0 }, Complex { re: 1, im: 0 }, Complex { re: 1, im: 0 }, Complex { re: 1, im: 0 }, Complex { re: 1, im: 0 }, Complex { re: 1, im: 0 }, Complex { re: 1, im: 0 }]`,
 right: `[Complex { re: 0, im: 0 }, Complex { re: 0, im: 0 }, Complex { re: 0, im: 0 }, Complex { re: 0, im: 0 }, Complex { re: 0, im: 0 }, Complex { re: 0, im: 0 }, Complex { re: 0, im: 0 }, Complex { re: 0, im: 0 }, Complex { re: 0, im: 0 }, Complex { re: 0, im: 0 }, Complex { re: 0, im: 0 }, Complex { re: 0, im: 0 }, Complex { re: 0, im: 0 }, Complex { re: 0, im: 0 }, Complex { re: 0, im: 0 }, Complex { re: 0, im: 0 }]`', src/lib.rs:13:1
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Erik.

**Comment by cuviper** [comment]
`Display` should already have that compact form, but there's a reasonable case to be made for `Debug` as well. We did make that change for `BigInt` and `BigUint` in rust-num/num-bigint#195, but it's somewhat debatable whether that should be considered a breaking change. In that case, I was getting ready for a semver bump anyway.

**Comment by ErikBuer** [comment]
Yes, I see now.
I appreciate the feedback!

Erik.

**Comment by edyounis** [comment]
Has there been any progress on this topic?

When testing/debugging complex matrix functions, `assert_eq` statements print complex numbers in their Debug representation. This causes headaches due to the unnecessarily verbose output of matrices. I am happy to put up a PR, if you would like.
