### ISSUE TITLE
Proposal: add support for Rust-CUDA

### ISSUE THREAD

**Issue by sebcrozet** [rust-num/num-complex#97]
The [Rust-CUDA](https://github.com/Rust-GPU/Rust-CUDA) project has been [announced](https://www.reddit.com/r/rust/comments/qzv428/announcing_the_rust_cuda_project_an_ecosystem_of) recently. It makes it straightforward to use existing `no-std` code on the GPU.

In order to be able to transfer a Rust type between the GPU VRAM, and the RAM, it is necessary for the type to implement the `cust::DeviceCopy` trait. 

Complex numbers are very useful for scientific computing and would be worth using on with CUDA. Would you be open to a PR on the `num-complex` crate that implements `DeviceCopy` for `Complex<T: DeviceCopy>`? This implementation would be enabled by an optional feature of course.

**Comment by cuviper** [comment]
Given that `cust` is a newer, faster-moving project -- 0.1.0 to 0.2.0 in just 4 days! -- I think it makes more sense to write that dependency in the other direction, as you have in <https://github.com/Rust-GPU/Rust-CUDA/pull/10>.
